extends: 'eslint:recommended'

env:
  node: true
  browser: true
  es6: true

parserOptions:
  sourceType: module

rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - always
